"""Staff report drafting from structured pipeline outputs.

The staff report is the document a hearing body actually reads: what is
proposed, what the analysis found, what the public said, and what staff
recommends under which conditions. This module assembles that document
from artifacts the pipeline already produces. Generation is template
driven and fully deterministic. Every sentence traces to a number or a
finding that appears elsewhere in the packet, which is the property that
makes a machine-drafted report reviewable; free-form generation was
rejected for exactly that reason.

The recommendation logic is mechanical and disclosed: any violation
finding forces DENY pending correction, cautions produce APPROVAL WITH
CONDITIONS with one condition per caution, and a clean report yields
APPROVAL. A human planner signs the real thing. The draft exists to save
the writing time, not the judgment.

Style is enforced, not requested: the emitted template text is checked
against a short list of banned constructions before the report is
returned. Matching is whole word, and header fields (site name, case
number, coordinates, date) are sanitized and masked out of the check,
so a place name that merely contains a banned stem can neither trip the
check nor crash generation.

Dependencies: none beyond the sibling planner modules whose outputs it
consumes (all optional arguments).
"""

import re

_BANNED_RE = tuple(re.compile(p, re.IGNORECASE) for p in (
    r"\bdelve[sd]?\b|\bdelving\b",
    r"\bshowcase[sd]?\b|\bshowcasing\b",
    r"\bleverage[sd]?\b|\bleveraging\b",
    r"\bvibrant\b",
    r"\btapestry\b|\btapestries\b",
    r"\bhonest(?:y|ly)?\b",
    r"\btestament\b",
    r"\bpivotal\b",
    r"\bcrucial(?:ly)?\b",
    r"\brobust(?:ly|ness)?\b",
    r"\bunderscore[sd]?\b|\bunderscoring\b",
    r"\bnot just\b",
    r"\bnot only\b",
))

_SEVERITY_ACTION = {
    "violation": "DENY pending correction",
    "caution": "APPROVE WITH CONDITIONS",
    None: "APPROVE",
}


def _style_check(text):
    """Reject banned constructions, matching whole words only, so a
    place name that contains a banned stem (Villa Robusta) passes."""
    hits = []
    if chr(0x2014) in text:
        hits.append("em dash (U+2014)")
    hits.extend(p.pattern for p in _BANNED_RE if p.search(text))
    if hits:
        raise ValueError(f"banned constructions in report: {hits}")
    return text


def _clean_meta(value, default):
    """Header fields land inside markdown, so newlines and heading
    marks are stripped before interpolation."""
    if value is None:
        return default
    s = str(value).replace("#", "").replace("\r", " ").replace("\n", " ")
    s = " ".join(s.split())
    return s if s else default


def _fmt_scores(scores_line):
    total, sub = scores_line
    if not sub:
        return f"total {total:.0f} of 100"
    top = sorted(sub.items(), key=lambda kv: -kv[1])[:3]
    top_keys = {k for k, _ in top}
    weak = [kv for kv in sorted(sub.items(), key=lambda kv: kv[1])
            if kv[0] not in top_keys][:2]
    out = (f"total {total:.0f} of 100; strongest on "
           + ", ".join(f"{k} ({v:.2f})" for k, v in top))
    if weak:
        out += ("; weakest on "
                + ", ".join(f"{k} ({v:.2f})" for k, v in weak))
    return out


def build_report(meta, ranked=None, zone_counts=None, findings=None,
                 comment_summary_md=None, forecast_info=None,
                 routing=None):
    """Assemble a draft staff report in markdown.

    meta: {"name", "lat", "lon", "date", "case_no"} strings for the
    header. ranked: {"order": [...], "scores": {i: (total, sub)}} from
    rank_samples. zone_counts: {class_name: px} for the preferred
    candidate. findings: list from compliance.check_plan. Optional
    comment_summary_md from public_comment.to_markdown, forecast_info
    from forecast.forecast, routing string from the mixture router.
    """
    findings = findings or []
    name = _clean_meta(meta.get("name"), "unnamed window")
    lat = _clean_meta(meta.get("lat"), "?")
    lon = _clean_meta(meta.get("lon"), "?")
    date = _clean_meta(meta.get("date"), "undated")
    case_no = _clean_meta(meta.get("case_no"), "no case number")
    lines = []
    lines.append("# Draft staff report: " + case_no)
    lines.append("")
    lines.append(f"Site: {name} ({lat}, {lon}). "
                 f"Date: {date}. Machine-drafted "
                 "from pipeline outputs; requires planner review and "
                 "signature before release.")
    lines.append("")

    lines.append("## Proposal")
    lines.append("")
    generated = ("Growth alternatives were generated by the "
                 + (f"{routing} expert of the " if routing else "")
                 + "terrain-conditioned diffusion model")
    if ranked and ranked.get("order"):
        order, scores = ranked["order"], ranked["scores"]
        n_metrics = len(scores[order[0]][1])
        if n_metrics:
            scorecard = f"the {n_metrics}-metric scorecard"
        else:
            scorecard = "the sustainability scorecard"
        lines.append(generated + " and scored by " + scorecard + ".")
        lines.append(f"{len(order)} alternatives were scored. The "
                     f"preferred alternative is candidate {order[0]}: "
                     + _fmt_scores(scores[order[0]]) + ".")
        if len(order) > 1:
            lines.append(f"The runner-up, candidate {order[1]}, scored "
                         + _fmt_scores(scores[order[1]]) + ".")
    else:
        lines.append(generated + ".")
    lines.append("")

    if zone_counts and any(zone_counts.values()):
        lines.append("## Land use composition of the preferred "
                     "alternative")
        lines.append("")
        total = sum(zone_counts.values()) or 1
        parts = [f"{k} {v} px ({v / total:.0%})"
                 for k, v in sorted(zone_counts.items(),
                                    key=lambda kv: -kv[1]) if v]
        lines.append("Typed growth: " + ", ".join(parts) + ".")
        lines.append("")

    if forecast_info:
        lines.append("## Growth outlook")
        lines.append("")
        note = str(forecast_info.get("note", "")).strip()
        if note:
            # capitalize the first character only, and never add a
            # second period after one the note already carries
            note = note[0].upper() + note[1:]
            if not note.endswith("."):
                note += "."
        lines.append((f"A {forecast_info['model']} fit to the five GHSL "
                      f"epochs projects {forecast_info['new_px']:.0f} new "
                      "built pixels by the target year "
                      f"({forecast_info['annual_px']:.1f} per year). "
                      + note).rstrip())
        lines.append("")

    if comment_summary_md:
        lines.append(comment_summary_md)
        lines.append("")

    from compliance import to_markdown as compliance_md
    lines.append(compliance_md(findings))
    lines.append("")

    worst = None
    for f in findings:
        if f["severity"] == "violation":
            worst = "violation"
            break
        if f["severity"] == "caution":
            worst = "caution"
    action = _SEVERITY_ACTION[worst]
    lines.append("## Staff recommendation (draft)")
    lines.append("")
    lines.append(f"Recommendation: {action}.")
    if worst == "caution":
        lines.append("Conditions:")
        for i, f in enumerate([f for f in findings
                               if f["severity"] == "caution"], 1):
            lines.append(f"{i}. Resolve finding {f['code']} before "
                         "final approval.")
    elif worst == "violation":
        lines.append("The violations listed above must be corrected and "
                     "the plan re-run before this application can "
                     "proceed.")
    lines.append("")
    lines.append("This recommendation was produced by a fixed rule over "
                 "the findings table and binds no one. Discretionary "
                 "findings, legal sufficiency, and the decision itself "
                 "rest with staff and the hearing body.")
    text = "\n".join(lines)
    # style-check the template text only: header fields are already
    # sanitized, and masking them keeps a site name from tripping the
    # check or blocking report generation
    masked = text
    for v in (name, lat, lon, date, case_no):
        if v:
            masked = masked.replace(v, " ")
    _style_check(masked)
    return text


if __name__ == "__main__":
    meta = {"name": "Gubbio test window", "lat": "43.3530",
            "lon": "12.5780", "date": "2026-07-05", "case_no": "PZ-26-041"}
    ranked = {"order": [2, 0, 1],
              "scores": {0: (44.0, {"coverage": 0.61, "infill": 0.20,
                                    "flood": 0.95}),
                         1: (41.0, {"coverage": 0.55, "infill": 0.25,
                                    "flood": 0.90}),
                         2: (51.0, {"coverage": 0.72, "infill": 0.31,
                                    "flood": 0.97})}}
    zone_counts = {"residential": 420, "commercial": 60, "mixed": 25}
    findings = [{"code": "A1", "severity": "caution", "count": 12,
                 "message": "12 residential pixels within 30 m of "
                 "industrial typing."}]
    fc = {"model": "logistic", "new_px": 310.0, "annual_px": 22.1,
          "note": "five-point fit; treat as an order of magnitude, "
          "not a target"}

    rep = build_report(meta, ranked, zone_counts, findings,
                       comment_summary_md=None, forecast_info=fc,
                       routing="town")
    assert rep.startswith("# Draft staff report: PZ-26-041"), rep[:60]
    assert "candidate 2" in rep and "51 of 100" in rep
    assert "APPROVE WITH CONDITIONS" in rep
    assert "Resolve finding A1" in rep
    assert "logistic fit" in rep and "310" in rep
    assert "requires planner review" in rep
    # metric count comes from the sub-scores, never a hardcoded eleven
    assert "3-metric scorecard" in rep, rep
    assert "eleven-metric" not in rep
    # forecast note keeps its own casing, single trailing period
    assert "not a target." in rep and "target.." not in rep

    clean = build_report(meta, ranked, zone_counts, [])
    assert "Recommendation: APPROVE." in clean
    bad = findings + [{"code": "W1", "severity": "violation", "count": 3,
                       "message": "3 growth pixels on water."}]
    deny = build_report(meta, ranked, zone_counts, bad)
    assert "DENY pending correction" in deny

    # without ranked, the report claims no scoring at all
    unranked = build_report(meta, None, zone_counts, [])
    assert "scored" not in unranked and "scorecard" not in unranked

    # a note with internal capitals and its own period survives intact
    fc2 = dict(fc); fc2["note"] = "GHSL epochs are coarse."
    repn = build_report(meta, None, None, [], forecast_info=fc2)
    assert "GHSL epochs are coarse." in repn and "coarse.." not in repn

    # single-metric and empty sub-score lines never repeat a metric
    s1 = _fmt_scores((40.0, {"coverage": 0.5}))
    assert s1.count("coverage") == 1, s1
    assert _fmt_scores((40.0, {})) == "total 40 of 100"

    # all-zero zone counts drop the composition section
    zeroed = build_report(meta, None, {"residential": 0}, [])
    assert "Land use composition" not in zeroed

    # place names containing a banned stem pass the whole-word check
    _style_check("the Villa Robusta annexation area")
    vmeta = dict(meta); vmeta["name"] = "Villa Robusta"
    assert "Villa Robusta" in build_report(vmeta, ranked, zone_counts, [])

    # header fields are sanitized and cannot crash generation
    messy = dict(meta)
    messy["name"] = "Vibrant\n# Heights"
    messy["case_no"] = "PZ#7\r\n"
    repm = build_report(messy, None, None, [])
    assert "# Draft staff report: PZ7" in repm
    assert "\n# Heights" not in repm

    try:
        _style_check("a truly vibrant tapestry of growth")
        raise AssertionError("style check let banned text through")
    except ValueError:
        pass
    try:
        _style_check("growth" + chr(0x2014) + "and more growth")
        raise AssertionError("style check let an em dash through")
    except ValueError:
        pass
    print("staff_report self-tests passed")
